### ISSUE TITLE
Facing issue after integration camaleon-spree

### ISSUE THREAD

**Issue by sonu1989** [owen2345/camaleon-spree#1]
Hi Team,

When I am trying to integrate this gem in my existing facing the below issue.
Any kind of help will be appreciated.
 `
NameError: uninitialized constant Plugins::CamaleonSpree::PrivateHelper
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/camaleon_spree-0.0.2/app/helpers/plugins/camaleon_spree/main_helper.rb:2:in `<module:MainHelper>'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/camaleon_spree-0.0.2/app/helpers/plugins/camaleon_spree/main_helper.rb:1:in `<top (required)>'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/actionpack-4.2.6/lib/abstract_controller/helpers.rb:149:in `block in modules_for_helpers'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/actionpack-4.2.6/lib/abstract_controller/helpers.rb:144:in `map!'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/actionpack-4.2.6/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/actionpack-4.2.6/lib/action_controller/metal/helpers.rb:93:in `modules_for_helpers'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/actionpack-4.2.6/lib/abstract_controller/helpers.rb:108:in `helper'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/actionpack-4.2.6/lib/action_controller/railties/helpers.rb:17:in `inherited'
/home/rails/rails_work/IndieInfluencers/app/controllers/application_controller.rb:1:in `<top (required)>'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/spree_api-3.1.5/config/initializers/metal_load_paths.rb:1:in `<top (required)>'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/home/rails/rails_work/IndieInfluencers/config/environment.rb:5:in `<top (required)>'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/bin/ruby_executable_hooks:15:in `eval'
/home/rails/.rvm/gems/ruby-2.2.2@indie_influencers/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spree_auth:admin:create => environment
(See full trace by running task with --trace)`

**Comment by owen2345** [comment]
This is because you need to buy the plugin from: http://camaleon.tuzitio.com/store/plugins/camaleon-spree
Enjoy Camaleon CMS!!!
